/*
 * Copyright (c) Jim Coles (jameskcoles@gmail.com) 2016. through present.
 *
 * Licensed under the following license agreement:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Also see the LICENSE file in the repository root directory.
 */

package org.jkcsoft.java.repos;

/**
 * This class generated by a code generation process:
 * Gen template: table-2-meta-class.vm
 * Gen date: Tue Aug 02 15:24:03 CDT 2005
 * <p>
 * RDB Table: BC_ATTRIBUTE
 */
public class Attribute extends FlexModelElement {
    // useful constants
    public static final String PROP_length = "length";
    public static final String PROP_parentEntityTypeOid = "parentEntityTypeOid";
    public static final String PROP_dataTypeOid = "dataTypeOid";
    public static final String PROP_toEntityTypeOid = "toEntityTypeOid";

    // properties
    private Long length; // LENGTH
    private Long parentEntityTypeOid; // PARENT_ENTITY_TYPE_OID
    private String parentEntityTypeName; // By Name ref for PARENT_ENTITY_TYPE_OID
    private Long dataTypeOid; // DATA_TYPE_OID
    private String dataTypeName; // By Name ref for DATA_TYPE_OID
    private Long toEntityTypeOid; // TO_ENTITY_TYPE_OID
    private String toEntityTypeName; // By Name ref for TO_ENTITY_TYPE_OID

    // getters and setters
    public Long getLength() {
        return length;
    }

    public void setLength(Long length) {
        this.length = length;
    }

    public void setLength(long length) {
        this.length = new Long(length);
    }

    public Long getParentEntityTypeOid() {
        return parentEntityTypeOid;
    }

    public void setParentEntityTypeOid(Long parentEntityTypeOid) {
        this.parentEntityTypeOid = parentEntityTypeOid;
    }

    public void setParentEntityTypeOid(long parentEntityTypeOid) {
        this.parentEntityTypeOid = new Long(parentEntityTypeOid);
    }

    public String getParentEntityTypeName() {
        return parentEntityTypeName;
    }

    public void setParentEntityTypeName(String parentEntityTypeName) {
        this.parentEntityTypeName = parentEntityTypeName;
    }


    public Long getDataTypeOid() {
        return dataTypeOid;
    }

    public void setDataTypeOid(Long dataTypeOid) {
        this.dataTypeOid = dataTypeOid;
    }

    public void setDataTypeOid(long dataTypeOid) {
        this.dataTypeOid = new Long(dataTypeOid);
    }

    public String getDataTypeName() {
        return dataTypeName;
    }

    public void setDataTypeName(String dataTypeName) {
        this.dataTypeName = dataTypeName;
    }


    public Long getToEntityTypeOid() {
        return toEntityTypeOid;
    }

    public void setToEntityTypeOid(Long toEntityTypeOid) {
        this.toEntityTypeOid = toEntityTypeOid;
    }

    public void setToEntityTypeOid(long toEntityTypeOid) {
        this.toEntityTypeOid = new Long(toEntityTypeOid);
    }

    public String getToEntityTypeName() {
        return toEntityTypeName;
    }

    public void setToEntityTypeName(String toEntityTypeName) {
        this.toEntityTypeName = toEntityTypeName;
    }


}

  
   

