/*
 * Copyright (c) Jim Coles (jameskcoles@gmail.com) 2016. through present.
 *
 * Licensed under the following license agreement:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Also see the LICENSE file in the repository root directory.
 */

package org.jkcsoft.java.repos;

/**
 * This class generated by a code generation process:
 * Gen template: table-2-meta-class.vm
 * Gen date: Thu Aug 04 18:24:51 CDT 2005
 * <p>
 * RDB Table: BC_ENTITY_TYPE
 */
public class EntityType extends FlexModelElement {
    // useful constants
    public static final String PROP_serviceGroupOid = "serviceGroupOid";
    public static final String PROP_isEnumerated = "isEnumerated";

    // properties
    private Long serviceGroupOid; // SERVICE_GROUP_OID
    private String serviceGroupName; // By Name ref for SERVICE_GROUP_OID
    private Long isEnumerated; // IS_ENUMERATED

    // getters and setters
    public Long getServiceGroupOid() {
        return serviceGroupOid;
    }

    public void setServiceGroupOid(Long serviceGroupOid) {
        this.serviceGroupOid = serviceGroupOid;
    }

    public void setServiceGroupOid(long serviceGroupOid) {
        this.serviceGroupOid = new Long(serviceGroupOid);
    }

    public String getServiceGroupName() {
        return serviceGroupName;
    }

    public void setServiceGroupName(String serviceGroupName) {
        this.serviceGroupName = serviceGroupName;
    }


    public Long getIsEnumerated() {
        return isEnumerated;
    }

    public void setIsEnumerated(Long isEnumerated) {
        this.isEnumerated = isEnumerated;
    }

    public void setIsEnumerated(long isEnumerated) {
        this.isEnumerated = new Long(isEnumerated);
    }


}

  
   

