/*
 * Copyright (c) Jim Coles (jameskcoles@gmail.com) 2016. through present.
 *
 * Licensed under the following license agreement:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Also see the LICENSE file in the repository root directory.
 */

package org.jkcsoft.java.repos;

/**
 * This class generated by a code generation process.
 * <p>
 * RDB Table: BC_ENTITY_PROCESS_STATUS
 */
public class EntityProcessStatus {
    // useful constants
    public static final String PROP_oid = "oid";
    public static final String PROP_creationDate = "creationDate";
    public static final String PROP_lastUpdatedDate = "lastUpdatedDate";
    public static final String PROP_actionNodeOid = "actionNodeOid";
    public static final String PROP_processEntityOid = "processEntityOid";
    public static final String PROP_assignedToOid = "assignedToOid";
    public static final String PROP_statusNodeOid = "statusNodeOid";

    // properties
    private Long oid; // OID
    private java.util.Date creationDate; // CREATION_DATE
    private java.util.Date lastUpdatedDate; // LAST_UPDATED_DATE
    private Long actionNodeOid; // ACTION_NODE_OID
    private Long processEntityOid; // PROCESS_ENTITY_OID
    private Long assignedToOid; // ASSIGNED_TO_OID
    private Long statusNodeOid; // STATUS_NODE_OID

    // getters and setters
    public Long getOid() {
        return oid;
    }

    public void setOid(Long oid) {
        this.oid = oid;
    }

    public void setOid(long oid) {
        this.oid = new Long(oid);
    }

    public java.util.Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(java.util.Date creationDate) {
        this.creationDate = creationDate;
    }

    public java.util.Date getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    public void setLastUpdatedDate(java.util.Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    public Long getActionNodeOid() {
        return actionNodeOid;
    }

    public void setActionNodeOid(Long actionNodeOid) {
        this.actionNodeOid = actionNodeOid;
    }

    public void setActionNodeOid(long actionNodeOid) {
        this.actionNodeOid = new Long(actionNodeOid);
    }

    public Long getProcessEntityOid() {
        return processEntityOid;
    }

    public void setProcessEntityOid(Long processEntityOid) {
        this.processEntityOid = processEntityOid;
    }

    public void setProcessEntityOid(long processEntityOid) {
        this.processEntityOid = new Long(processEntityOid);
    }

    public Long getAssignedToOid() {
        return assignedToOid;
    }

    public void setAssignedToOid(Long assignedToOid) {
        this.assignedToOid = assignedToOid;
    }

    public void setAssignedToOid(long assignedToOid) {
        this.assignedToOid = new Long(assignedToOid);
    }

    public Long getStatusNodeOid() {
        return statusNodeOid;
    }

    public void setStatusNodeOid(Long statusNodeOid) {
        this.statusNodeOid = statusNodeOid;
    }

    public void setStatusNodeOid(long statusNodeOid) {
        this.statusNodeOid = new Long(statusNodeOid);
    }

    // override Object.toString()
    public String toString() {
        String s = "EntityProcessStatus => "
                + " [oid] " + oid
                + " [creationDate] " + creationDate
                + " [lastUpdatedDate] " + lastUpdatedDate
                + " [actionNodeOid] " + actionNodeOid
                + " [processEntityOid] " + processEntityOid
                + " [assignedToOid] " + assignedToOid
                + " [statusNodeOid] " + statusNodeOid
                + " | Super => " + super.toString();

        return s;
    }
}

  
   

