/*
 * Copyright (c) Jim Coles (jameskcoles@gmail.com) 2016. through present.
 *
 * Licensed under the following license agreement:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Also see the LICENSE file in the repository root directory.
 */

package org.jkcsoft.java.repos;

/**
 * This class generated by a code generation process.
 * <p>
 * RDB Table: BC_TYPE_ENUMERATION
 */
public class FlexModel {
    // useful constants
    public static final String PROP_oid = "oid";
    public static final String PROP_creationDate = "creationDate";
    public static final String PROP_lastUpdatedDate = "lastUpdatedDate";
    public static final String PROP_codeName = "codeName";
    public static final String PROP_description = "description";
    public static final String PROP_displayName = "displayName";
    public static final String PROP_entityTypeOid = "entityTypeOid";

    // properties
    private Long oid; // OID
    private java.util.Date creationDate; // CREATION_DATE
    private java.util.Date lastUpdatedDate; // LAST_UPDATED_DATE
    private String codeName; // CODE_NAME
    private String description; // DESCRIPTION
    private String displayName; // DISPLAY_NAME
    private Long entityTypeOid; // ENTITY_TYPE_OID

    // getters and setters
    public Long getOid() {
        return oid;
    }

    public void setOid(Long oid) {
        this.oid = oid;
    }

    public void setOid(long oid) {
        this.oid = new Long(oid);
    }

    public java.util.Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(java.util.Date creationDate) {
        this.creationDate = creationDate;
    }

    public java.util.Date getLastUpdatedDate() {
        return lastUpdatedDate;
    }

    public void setLastUpdatedDate(java.util.Date lastUpdatedDate) {
        this.lastUpdatedDate = lastUpdatedDate;
    }

    public String getCodeName() {
        return codeName;
    }

    public void setCodeName(String codeName) {
        this.codeName = codeName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public Long getEntityTypeOid() {
        return entityTypeOid;
    }

    public void setEntityTypeOid(Long entityTypeOid) {
        this.entityTypeOid = entityTypeOid;
    }

    public void setEntityTypeOid(long entityTypeOid) {
        this.entityTypeOid = new Long(entityTypeOid);
    }

    // override Object.toString()
    public String toString() {
        String s = "TypeEnumeration => "
                + " [oid] " + oid
                + " [creationDate] " + creationDate
                + " [lastUpdatedDate] " + lastUpdatedDate
                + " [codeName] " + codeName
                + " [description] " + description
                + " [displayName] " + displayName
                + " [entityTypeOid] " + entityTypeOid
                + " | Super => " + super.toString();

        return s;
    }
}

  
   

