/*
 * Copyright (c) Jim Coles (jameskcoles@gmail.com) 2016. through present.
 *
 * Licensed under the following license agreement:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Also see the LICENSE file in the repository root directory.
 */

package org.jkcsoft.java.repos;

/**
 * This class generated by a code generation process:
 * Gen template: table-2-meta-class.vm
 * Gen date: Tue Aug 02 15:24:04 CDT 2005
 * <p>
 * RDB Table: BC_NODE_CONSTRAINT
 */
public class NodeConstraint extends FlexModelElement {
    // useful constants
    public static final String PROP_fromNodeOid = "fromNodeOid";
    public static final String PROP_constraintTypeOid = "constraintTypeOid";
    public static final String PROP_toNodeOid = "toNodeOid";

    // properties
    private Long fromNodeOid; // FROM_NODE_OID
    private Long constraintTypeOid; // CONSTRAINT_TYPE_OID
    private String constraintTypeName; // By Name ref for CONSTRAINT_TYPE_OID
    private Long toNodeOid; // TO_NODE_OID

    // getters and setters
    public Long getFromNodeOid() {
        return fromNodeOid;
    }

    public void setFromNodeOid(Long fromNodeOid) {
        this.fromNodeOid = fromNodeOid;
    }

    public void setFromNodeOid(long fromNodeOid) {
        this.fromNodeOid = new Long(fromNodeOid);
    }

    public Long getConstraintTypeOid() {
        return constraintTypeOid;
    }

    public void setConstraintTypeOid(Long constraintTypeOid) {
        this.constraintTypeOid = constraintTypeOid;
    }

    public void setConstraintTypeOid(long constraintTypeOid) {
        this.constraintTypeOid = new Long(constraintTypeOid);
    }

    public String getConstraintTypeName() {
        return constraintTypeName;
    }

    public void setConstraintTypeName(String constraintTypeName) {
        this.constraintTypeName = constraintTypeName;
    }


    public Long getToNodeOid() {
        return toNodeOid;
    }

    public void setToNodeOid(Long toNodeOid) {
        this.toNodeOid = toNodeOid;
    }

    public void setToNodeOid(long toNodeOid) {
        this.toNodeOid = new Long(toNodeOid);
    }


}

  
   

