/*
 * Copyright (c) Jim Coles (jameskcoles@gmail.com) 2016. through present.
 *
 * Licensed under the following license agreement:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Also see the LICENSE file in the repository root directory.
 */

package org.jkcsoft.java.repos;

/**
 * This class generated by a code generation process:
 * Gen template: table-2-meta-class.vm
 * Gen date: Tue Aug 02 15:24:05 CDT 2005
 * <p>
 * RDB Table: BC_RELATIONSHIP_TYPE
 */
public class RelationshipType extends FlexModelElement {
    // useful constants

    // properties

    // getters and setters

}

  
   

