/*
 * Copyright (c) Jim Coles (jameskcoles@gmail.com) 2016. through present.
 *
 * Licensed under the following license agreement:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Also see the LICENSE file in the repository root directory.
 */

package org.jkcsoft.java.repos;

/**
 * This class generated by a code generation process.
 * <p>
 * RDB Table: BC_USER
 */
public class User {
    // useful constants
    public static final String PROP_oid = "oid";
    public static final String PROP_username = "username";
    public static final String PROP_password = "password";
    public static final String PROP_personOid = "personOid";

    // properties
    private Long oid; // OID
    private String username; // USERNAME
    private String password; // PASSWORD
    private Long personOid; // PERSON_OID

    // getters and setters
    public Long getOid() {
        return oid;
    }

    public void setOid(Long oid) {
        this.oid = oid;
    }

    public void setOid(long oid) {
        this.oid = new Long(oid);
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Long getPersonOid() {
        return personOid;
    }

    public void setPersonOid(Long personOid) {
        this.personOid = personOid;
    }

    public void setPersonOid(long personOid) {
        this.personOid = new Long(personOid);
    }

    // override Object.toString()
    public String toString() {
        String s = "User => "
                + " [oid] " + oid
                + " [username] " + username
                + " [password] " + password
                + " [personOid] " + personOid
                + " | Super => " + super.toString();

        return s;
    }
}

  
   

