/*
 * Copyright (c) Jim Coles (jameskcoles@gmail.com) 2018 through present.
 *
 * Licensed under the following license agreement:
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Also see the LICENSE file in the repository root directory.
 */

package org.jkcsoft.java.repos;

/**
 * This class generated by a code generation process.
 * <p>
 * RDB Table: BC_ACTIVITY_ATTR_CONSTRAINT
 */
public class ActivityAttrConstraint {
    // useful constants
    public static final String PROP_oid = "oid";
    public static final String PROP_codeName = "codeName";
    public static final String PROP_description = "description";
    public static final String PROP_processNodeOid = "processNodeOid";
    public static final String PROP_attributeOid = "attributeOid";

    // properties
    private Long oid; // OID
    private String codeName; // CODE_NAME
    private String description; // DESCRIPTION
    private Long processNodeOid; // PROCESS_NODE_OID
    private Long attributeOid; // ATTRIBUTE_OID

    // getters and setters
    public Long getOid() {
        return oid;
    }

    public void setOid(Long oid) {
        this.oid = oid;
    }

    public void setOid(long oid) {
        this.oid = new Long(oid);
    }

    public String getCodeName() {
        return codeName;
    }

    public void setCodeName(String codeName) {
        this.codeName = codeName;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getProcessNodeOid() {
        return processNodeOid;
    }

    public void setProcessNodeOid(Long processNodeOid) {
        this.processNodeOid = processNodeOid;
    }

    public void setProcessNodeOid(long processNodeOid) {
        this.processNodeOid = new Long(processNodeOid);
    }

    public Long getAttributeOid() {
        return attributeOid;
    }

    public void setAttributeOid(Long attributeOid) {
        this.attributeOid = attributeOid;
    }

    public void setAttributeOid(long attributeOid) {
        this.attributeOid = new Long(attributeOid);
    }

    // override Object.toString()
    public String toString() {
        String s = "ActivityAttrConstraint => "
                + " [oid] " + oid
                + " [codeName] " + codeName
                + " [description] " + description
                + " [processNodeOid] " + processNodeOid
                + " [attributeOid] " + attributeOid
                + " | Super => " + super.toString();

        return s;
    }
}

  
   

