/*
 * Copyright (c) Jim Coles (jameskcoles@gmail.com) 2018 through present.
 *
 * Licensed under the following license agreement:
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Also see the LICENSE file in the repository root directory.
 */

package org.jkcsoft.java.repos;

/**
 * This class generated by a code generation process.
 * <p>
 * RDB Table: BC_ATTRIBUTE_CHANGE_HISTORY
 */
public class AttributeChangeHistory {
    // useful constants
    public static final String PROP_oid = "oid";
    public static final String PROP_parentObjectOid = "parentObjectOid";
    public static final String PROP_dateCreated = "dateCreated";
    public static final String PROP_oldAttributeValue = "oldAttributeValue";
    public static final String PROP_historyPersonOid = "historyPersonOid";
    public static final String PROP_attributeOid = "attributeOid";
    public static final String PROP_newAttributeValue = "newAttributeValue";

    // properties
    private Long oid; // OID
    private String parentObjectOid; // PARENT_OBJECT_OID
    private String dateCreated; // DATE_CREATED
    private String oldAttributeValue; // OLD_ATTRIBUTE_VALUE
    private Long historyPersonOid; // HISTORY_PERSON_OID
    private Long attributeOid; // ATTRIBUTE_OID
    private String newAttributeValue; // NEW_ATTRIBUTE_VALUE

    // getters and setters
    public Long getOid() {
        return oid;
    }

    public void setOid(Long oid) {
        this.oid = oid;
    }

    public void setOid(long oid) {
        this.oid = new Long(oid);
    }

    public String getParentObjectOid() {
        return parentObjectOid;
    }

    public void setParentObjectOid(String parentObjectOid) {
        this.parentObjectOid = parentObjectOid;
    }

    public String getDateCreated() {
        return dateCreated;
    }

    public void setDateCreated(String dateCreated) {
        this.dateCreated = dateCreated;
    }

    public String getOldAttributeValue() {
        return oldAttributeValue;
    }

    public void setOldAttributeValue(String oldAttributeValue) {
        this.oldAttributeValue = oldAttributeValue;
    }

    public Long getHistoryPersonOid() {
        return historyPersonOid;
    }

    public void setHistoryPersonOid(Long historyPersonOid) {
        this.historyPersonOid = historyPersonOid;
    }

    public void setHistoryPersonOid(long historyPersonOid) {
        this.historyPersonOid = new Long(historyPersonOid);
    }

    public Long getAttributeOid() {
        return attributeOid;
    }

    public void setAttributeOid(Long attributeOid) {
        this.attributeOid = attributeOid;
    }

    public void setAttributeOid(long attributeOid) {
        this.attributeOid = new Long(attributeOid);
    }

    public String getNewAttributeValue() {
        return newAttributeValue;
    }

    public void setNewAttributeValue(String newAttributeValue) {
        this.newAttributeValue = newAttributeValue;
    }

    // override Object.toString()
    public String toString() {
        String s = "AttributeChangeHistory => "
                + " [oid] " + oid
                + " [parentObjectOid] " + parentObjectOid
                + " [dateCreated] " + dateCreated
                + " [oldAttributeValue] " + oldAttributeValue
                + " [historyPersonOid] " + historyPersonOid
                + " [attributeOid] " + attributeOid
                + " [newAttributeValue] " + newAttributeValue
                + " | Super => " + super.toString();

        return s;
    }
}

  
   

