/*
 * Copyright (c) Jim Coles (jameskcoles@gmail.com) 2018 through present.
 *
 * Licensed under the following license agreement:
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Also see the LICENSE file in the repository root directory.
 */

package org.jkcsoft.java.repos;

/**
 * This class generated by a code generation process:
 * Gen template: table-2-meta-class.vm
 * Gen date: Tue Aug 02 15:24:03 CDT 2005
 * <p>
 * RDB Table: BC_BUSINESS_PROCESS
 */
public class BusinessProcess extends FlexModelElement {
    // useful constants
    public static final String PROP_processEntityTypeOid = "processEntityTypeOid";

    // properties
    private Long processEntityTypeOid; // PROCESS_ENTITY_TYPE_OID
    private String processEntityTypeName; // By Name ref for PROCESS_ENTITY_TYPE_OID

    // getters and setters
    public Long getProcessEntityTypeOid() {
        return processEntityTypeOid;
    }

    public void setProcessEntityTypeOid(Long processEntityTypeOid) {
        this.processEntityTypeOid = processEntityTypeOid;
    }

    public void setProcessEntityTypeOid(long processEntityTypeOid) {
        this.processEntityTypeOid = new Long(processEntityTypeOid);
    }

    public String getProcessEntityTypeName() {
        return processEntityTypeName;
    }

    public void setProcessEntityTypeName(String processEntityTypeName) {
        this.processEntityTypeName = processEntityTypeName;
    }


}

  
   

