/*
 * Copyright (c) Jim Coles (jameskcoles@gmail.com) 2018 through present.
 *
 * Licensed under the following license agreement:
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Also see the LICENSE file in the repository root directory.
 */

package org.jkcsoft.java.repos;

/**
 * This class generated by a code generation process.
 * <p>
 * RDB Table: BC_PROCESS_CHANGE_HISTORY
 */
public class ProcessChangeHistory {
    // useful constants
    public static final String PROP_oid = "oid";
    public static final String PROP_parentObjectOid = "parentObjectOid";
    public static final String PROP_creationDate = "creationDate";
    public static final String PROP_oldStatusValue = "oldStatusValue";
    public static final String PROP_historyPersonOid = "historyPersonOid";
    public static final String PROP_newStatusValue = "newStatusValue";
    public static final String PROP_actionNodeOid = "actionNodeOid";

    // properties
    private Long oid; // OID
    private Long parentObjectOid; // PARENT_OBJECT_OID
    private java.util.Date creationDate; // CREATION_DATE
    private String oldStatusValue; // OLD_STATUS_VALUE
    private Long historyPersonOid; // HISTORY_PERSON_OID
    private String newStatusValue; // NEW_STATUS_VALUE
    private Long actionNodeOid; // ACTION_NODE_OID

    // getters and setters
    public Long getOid() {
        return oid;
    }

    public void setOid(Long oid) {
        this.oid = oid;
    }

    public void setOid(long oid) {
        this.oid = new Long(oid);
    }

    public Long getParentObjectOid() {
        return parentObjectOid;
    }

    public void setParentObjectOid(Long parentObjectOid) {
        this.parentObjectOid = parentObjectOid;
    }

    public void setParentObjectOid(long parentObjectOid) {
        this.parentObjectOid = new Long(parentObjectOid);
    }

    public java.util.Date getCreationDate() {
        return creationDate;
    }

    public void setCreationDate(java.util.Date creationDate) {
        this.creationDate = creationDate;
    }

    public String getOldStatusValue() {
        return oldStatusValue;
    }

    public void setOldStatusValue(String oldStatusValue) {
        this.oldStatusValue = oldStatusValue;
    }

    public Long getHistoryPersonOid() {
        return historyPersonOid;
    }

    public void setHistoryPersonOid(Long historyPersonOid) {
        this.historyPersonOid = historyPersonOid;
    }

    public void setHistoryPersonOid(long historyPersonOid) {
        this.historyPersonOid = new Long(historyPersonOid);
    }

    public String getNewStatusValue() {
        return newStatusValue;
    }

    public void setNewStatusValue(String newStatusValue) {
        this.newStatusValue = newStatusValue;
    }

    public Long getActionNodeOid() {
        return actionNodeOid;
    }

    public void setActionNodeOid(Long actionNodeOid) {
        this.actionNodeOid = actionNodeOid;
    }

    public void setActionNodeOid(long actionNodeOid) {
        this.actionNodeOid = new Long(actionNodeOid);
    }

    // override Object.toString()
    public String toString() {
        String s = "ProcessChangeHistory => "
                + " [oid] " + oid
                + " [parentObjectOid] " + parentObjectOid
                + " [creationDate] " + creationDate
                + " [oldStatusValue] " + oldStatusValue
                + " [historyPersonOid] " + historyPersonOid
                + " [newStatusValue] " + newStatusValue
                + " [actionNodeOid] " + actionNodeOid
                + " | Super => " + super.toString();

        return s;
    }
}

  
   

