/*
 * Copyright (c) Jim Coles (jameskcoles@gmail.com) 2018 through present.
 *
 * Licensed under the following license agreement:
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Also see the LICENSE file in the repository root directory.
 */

package org.jkcsoft.java.repos;

/**
 * This class generated by a code generation process:
 * Gen template: table-2-meta-class.vm
 * Gen date: Thu Aug 04 18:24:52 CDT 2005
 * <p>
 * RDB Table: BC_PROCESS_NODE
 */
public class ProcessNode extends FlexModelElement {
    // useful constants
    public static final String PROP_processOid = "processOid";
    public static final String PROP_subProcessOid = "subProcessOid";
    public static final String PROP_nodeTypeOid = "nodeTypeOid";
    public static final String PROP_isStartNode = "isStartNode";
    public static final String PROP_serviceGroupOid = "serviceGroupOid";
    public static final String PROP_defaultAssigneeOid = "defaultAssigneeOid";

    // properties
    private Long processOid; // PROCESS_OID
    private String processName; // By Name ref for PROCESS_OID
    private Long subProcessOid; // SUB_PROCESS_OID
    private String subProcessName; // By Name ref for SUB_PROCESS_OID
    private Long nodeTypeOid; // NODE_TYPE_OID
    private String nodeTypeName; // By Name ref for NODE_TYPE_OID
    private Long isStartNode; // IS_START_NODE
    private Long serviceGroupOid; // SERVICE_GROUP_OID
    private String serviceGroupName; // By Name ref for SERVICE_GROUP_OID
    private Long defaultAssigneeOid; // DEFAULT_ASSIGNEE_OID
    private String defaultAssigneeName; // By Name ref for DEFAULT_ASSIGNEE_OID

    // getters and setters
    public Long getProcessOid() {
        return processOid;
    }

    public void setProcessOid(Long processOid) {
        this.processOid = processOid;
    }

    public void setProcessOid(long processOid) {
        this.processOid = new Long(processOid);
    }

    public String getProcessName() {
        return processName;
    }

    public void setProcessName(String processName) {
        this.processName = processName;
    }


    public Long getSubProcessOid() {
        return subProcessOid;
    }

    public void setSubProcessOid(Long subProcessOid) {
        this.subProcessOid = subProcessOid;
    }

    public void setSubProcessOid(long subProcessOid) {
        this.subProcessOid = new Long(subProcessOid);
    }

    public String getSubProcessName() {
        return subProcessName;
    }

    public void setSubProcessName(String subProcessName) {
        this.subProcessName = subProcessName;
    }


    public Long getNodeTypeOid() {
        return nodeTypeOid;
    }

    public void setNodeTypeOid(Long nodeTypeOid) {
        this.nodeTypeOid = nodeTypeOid;
    }

    public void setNodeTypeOid(long nodeTypeOid) {
        this.nodeTypeOid = new Long(nodeTypeOid);
    }

    public String getNodeTypeName() {
        return nodeTypeName;
    }

    public void setNodeTypeName(String nodeTypeName) {
        this.nodeTypeName = nodeTypeName;
    }


    public Long getIsStartNode() {
        return isStartNode;
    }

    public void setIsStartNode(Long isStartNode) {
        this.isStartNode = isStartNode;
    }

    public void setIsStartNode(long isStartNode) {
        this.isStartNode = new Long(isStartNode);
    }

    public Long getServiceGroupOid() {
        return serviceGroupOid;
    }

    public void setServiceGroupOid(Long serviceGroupOid) {
        this.serviceGroupOid = serviceGroupOid;
    }

    public void setServiceGroupOid(long serviceGroupOid) {
        this.serviceGroupOid = new Long(serviceGroupOid);
    }

    public String getServiceGroupName() {
        return serviceGroupName;
    }

    public void setServiceGroupName(String serviceGroupName) {
        this.serviceGroupName = serviceGroupName;
    }


    public Long getDefaultAssigneeOid() {
        return defaultAssigneeOid;
    }

    public void setDefaultAssigneeOid(Long defaultAssigneeOid) {
        this.defaultAssigneeOid = defaultAssigneeOid;
    }

    public void setDefaultAssigneeOid(long defaultAssigneeOid) {
        this.defaultAssigneeOid = new Long(defaultAssigneeOid);
    }

    public String getDefaultAssigneeName() {
        return defaultAssigneeName;
    }

    public void setDefaultAssigneeName(String defaultAssigneeName) {
        this.defaultAssigneeName = defaultAssigneeName;
    }


}

  
   

