/*
 * Copyright (c) Jim Coles (jameskcoles@gmail.com) 2018 through present.
 *
 * Licensed under the following license agreement:
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Also see the LICENSE file in the repository root directory.
 */

package org.jkcsoft.java.repos;

/**
 * This class generated by a code generation process.
 * <p>
 * RDB Table: BC_STRING_ATTR_VALUE
 */
public class StringAttrValue {
    // useful constants
    public static final String PROP_oid = "oid";
    public static final String PROP_value = "value";
    public static final String PROP_parentOid = "parentOid";
    public static final String PROP_attributeOid = "attributeOid";

    // properties
    private Long oid; // OID
    private String value; // VALUE
    private Long parentOid; // PARENT_OID
    private Long attributeOid; // ATTRIBUTE_OID

    // getters and setters
    public Long getOid() {
        return oid;
    }

    public void setOid(Long oid) {
        this.oid = oid;
    }

    public void setOid(long oid) {
        this.oid = new Long(oid);
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public Long getParentOid() {
        return parentOid;
    }

    public void setParentOid(Long parentOid) {
        this.parentOid = parentOid;
    }

    public void setParentOid(long parentOid) {
        this.parentOid = new Long(parentOid);
    }

    public Long getAttributeOid() {
        return attributeOid;
    }

    public void setAttributeOid(Long attributeOid) {
        this.attributeOid = attributeOid;
    }

    public void setAttributeOid(long attributeOid) {
        this.attributeOid = new Long(attributeOid);
    }

    // override Object.toString()
    public String toString() {
        String s = "StringAttrValue => "
                + " [oid] " + oid
                + " [value] " + value
                + " [parentOid] " + parentOid
                + " [attributeOid] " + attributeOid
                + " | Super => " + super.toString();

        return s;
    }
}

  
   

